import PDFDocument from "pdfkit";

import Bill from "../models/billModel.js";

// ================= GENERATE PDF =================

export const generateBillPDF = async (req, res) => {
  try {
    const { id } = req.params;

    // 🔐 ownership protection
    const bill = await Bill.findOne({
      _id: id,
      user: req.user._id,
    }).populate("customer");

    if (!bill) {
      return res.status(404).json({
        error: "Bill not found",
      });
    }

    // ================= PDF INIT =================

    const doc = new PDFDocument({
      margin: 40,
    });

    // ================= HEADERS =================

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      `inline; filename=${bill.lotNumber}.pdf`,
    );

    doc.pipe(res);

    // ================= TITLE =================

    doc.fontSize(22).text("Delivery Bill", {
      align: "center",
    });

    doc.moveDown(2);

    // ================= BILL INFO =================

    doc.fontSize(12);

    doc.text(`Lot Number: ${bill.lotNumber.split("-")[1]}`);

    doc.text(`Vehicle Number: ${bill.vehicleNumber || "-"}`);

    doc.text(`Date: ${new Date(bill.deliveryDate).toLocaleDateString()}`);

    doc.moveDown();

    // ================= FROM / TO =================

    doc.text(`From: ${bill.fromName}`);
   if (bill.address) {
      doc.text(`Address: ${bill.address}`);
    }

    doc.text(`To: ${bill.customer?.name || "-"}`);

    if (bill.customer?.address) {
      doc.text(`Address: ${bill.customer.address}`);
    }

    doc.moveDown(2);

    // ================= TABLE HEADER =================

    const tableTop = 250;

    doc.fontSize(12);

    doc.text("Label", 50, tableTop);

    doc.text("Qty", 180, tableTop);

    doc.text("Rate", 280, tableTop);

    doc.text("Total", 400, tableTop);

    // ================= HEADER LINE =================

    doc
      .moveTo(40, tableTop + 20)
      .lineTo(550, tableTop + 20)
      .stroke();

    // ================= ROWS =================

    let y = tableTop + 40;

    bill.rows.forEach((row) => {
      const total = row.amount || row.quantity * row.rate;

      doc.text(row.label, 50, y);

      doc.text(String(row.quantity), 180, y);

      doc.text(`Rs. ${row.rate}`, 280, y);

      doc.text(`Rs. ${total}`, 400, y);

      y += 30;
    });

    // ================= TOTAL SECTION =================

    y += 10;

    doc.moveTo(300, y).lineTo(550, y).stroke();

    y += 20;

    // SAME FONT SIZE
    doc.fontSize(13);

    doc.text(`Total Quantity: ${bill.totalQuantity}`, 300, y);

    y += 30;

    doc.text(`Total Amount: Rs. ${bill.totalAmount}`, 300, y);

    // ================= NOTES =================

    if (bill.notes) {
      y += 50;

      doc.fontSize(12);

      doc.text(`Notes: ${bill.notes}`, 50, y);
    }

    // ================= FOOTER =================

    const pageHeight = doc.page.height;

    doc.fontSize(10).text("Generated by BillingIT", 0, pageHeight - 50, {
      align: "center",
      width: doc.page.width,
    });

    // ================= FINISH =================

    doc.end();
  } catch (error) {
    return res.status(500).json({
      error: error.message,
    });
  }
};
