import PDFDocument from "pdfkit";

import Bill from "../models/billModel.js";

// ================= GENERATE PDF =================

export const generateBillPDF = async (req, res) => {
  try {
    const { id } = req.params;

    // 🔐 ownership protection
    const bill = await Bill.findOne({
      _id: id,

      user: req.user._id,
    });

    if (!bill) {
      return res.status(404).json({
        error: "Bill not found",
      });
    }

    // ================= PDF INIT =================

    const doc = new PDFDocument({
      margin: 40,
    });

    // 🔥 headers
    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      `inline; filename=${bill.lotNumber}.pdf`,
    );

    doc.pipe(res);

    // ================= TITLE =================

    doc.fontSize(22).text("DELIVERY CHALLAN", {
      align: "center",
    });

    doc.moveDown(2);

    // ================= BILL INFO =================

    doc.fontSize(12).text(`Lot Number: ${bill.lotNumber}`);

    doc.text(`Vehicle Number: ${bill.vehicleNumber || "-"}`);

    doc.text(`Date: ${new Date(bill.deliveryDate).toLocaleDateString()}`);

    doc.moveDown();

    // ================= FROM / TO =================

    doc.text(`From: ${bill.fromName}`);

    doc.text(`To: ${bill.toName}`);

    if (bill.address) {
      doc.text(`Address: ${bill.address}`);
    }

    doc.moveDown(2);

    // ================= TABLE HEADER =================

    const tableTop = 250;

    doc.fontSize(12).text("Label", 50, tableTop);

    doc.text("Qty", 200, tableTop);

    doc.text("Rate", 300, tableTop);

    doc.text("Amount", 420, tableTop);

    // line
    doc
      .moveTo(40, tableTop + 20)
      .lineTo(550, tableTop + 20)
      .stroke();

    // ================= ROWS =================

    let y = tableTop + 40;

    bill.rows.forEach((row) => {
      doc.text(row.label, 50, y);

      doc.text(row.quantity.toString(), 200, y);

      doc.text(row.rate.toString(), 300, y);

      doc.text(row.amount.toString(), 420, y);

      y += 25;
    });

    // ================= TOTALS =================

    y += 20;

    doc.moveTo(300, y).lineTo(550, y).stroke();

    y += 15;

    doc.text(`Total Quantity: ${bill.totalQuantity}`, 300, y);

    y += 25;

    doc.fontSize(14).text(`Grand Total: ₹${bill.grandTotal}`, 300, y);

    // ================= NOTES =================

    if (bill.notes) {
      y += 40;

      doc.fontSize(12).text(`Notes: ${bill.notes}`, 50, y);
    }

    // ================= FOOTER =================

    doc.moveDown(5);

    doc.fontSize(10).text("Generated by Billing System", {
      align: "center",
    });

    // finish
    doc.end();
  } catch (error) {
    return res.status(500).json({
      error: error.message,
    });
  }
};
import PDFDocument from "pdfkit";

import Bill from "../models/billModel.js";

// ================= GENERATE PDF =================

export const generateBillPDF = async (req, res) => {
  try {
    const { id } = req.params;

    // 🔐 ownership protection
    const bill = await Bill.findOne({
      _id: id,

      user: req.user._id,
    });

    if (!bill) {
      return res.status(404).json({
        error: "Bill not found",
      });
    }

    // ================= PDF INIT =================

    const doc = new PDFDocument({
      margin: 40,
    });

    // 🔥 headers
    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      `inline; filename=${bill.lotNumber}.pdf`,
    );

    doc.pipe(res);

    // ================= TITLE =================

    doc.fontSize(22).text("DELIVERY CHALLAN", {
      align: "center",
    });

    doc.moveDown(2);

    // ================= BILL INFO =================

    doc.fontSize(12).text(`Lot Number: ${bill.lotNumber}`);

    doc.text(`Vehicle Number: ${bill.vehicleNumber || "-"}`);

    doc.text(`Date: ${new Date(bill.deliveryDate).toLocaleDateString()}`);

    doc.moveDown();

    // ================= FROM / TO =================

    doc.text(`From: ${bill.fromName}`);

    doc.text(`To: ${bill.toName}`);

    if (bill.address) {
      doc.text(`Address: ${bill.address}`);
    }

    doc.moveDown(2);

    // ================= TABLE HEADER =================

    const tableTop = 250;

    doc.fontSize(12).text("Label", 50, tableTop);

    doc.text("Qty", 200, tableTop);

    doc.text("Rate", 300, tableTop);

    doc.text("Amount", 420, tableTop);

    // line
    doc
      .moveTo(40, tableTop + 20)
      .lineTo(550, tableTop + 20)
      .stroke();

    // ================= ROWS =================

    let y = tableTop + 40;

    bill.rows.forEach((row) => {
      doc.text(row.label, 50, y);

      doc.text(row.quantity.toString(), 200, y);

      doc.text(row.rate.toString(), 300, y);

      doc.text(row.amount.toString(), 420, y);

      y += 25;
    });

    // ================= TOTALS =================

    y += 20;

    doc.moveTo(300, y).lineTo(550, y).stroke();

    y += 15;

    doc.text(`Total Quantity: ${bill.totalQuantity}`, 300, y);

    y += 25;

    doc.fontSize(14).text(`Grand Total: ₹${bill.grandTotal}`, 300, y);

    // ================= NOTES =================

    if (bill.notes) {
      y += 40;

      doc.fontSize(12).text(`Notes: ${bill.notes}`, 50, y);
    }

    // ================= FOOTER =================

    doc.moveDown(5);

    doc.fontSize(10).text("Generated by Billing System", {
      align: "center",
    });

    // finish
    doc.end();
  } catch (error) {
    return res.status(500).json({
      error: error.message,
    });
  }
};
